"""nullable true on zip

Revision ID: 70b9110642ed
Revises: ed9531a082fc
Create Date: 2023-08-15 15:30:00.563557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b9110642ed'
down_revision = 'ed9531a082fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_unique_constraint('uq_lakes_address', ['address'])
        batch_op.drop_column('address1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address1', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('uq_lakes_address', type_='unique')
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('address')

    # ### end Alembic commands ###
