"""add image and season to fish table

Revision ID: e171af0b33af
Revises: ed0e2df717ba
Create Date: 2023-08-15 16:22:36.274182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e171af0b33af'
down_revision = 'ed0e2df717ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('start_season', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_season', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fish', schema=None) as batch_op:
        batch_op.drop_column('end_season')
        batch_op.drop_column('start_season')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
