"""unique lat and lng

Revision ID: ed0e2df717ba
Revises: 70b9110642ed
Create Date: 2023-08-15 15:34:54.945562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0e2df717ba'
down_revision = '70b9110642ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lakes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_lng', ['lng'])
        batch_op.create_unique_constraint('uq_lat', ['lat'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lakes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_lng', type_='unique')
        batch_op.drop_constraint('uq_lat', type_='unique')

    # ### end Alembic commands ###
